### PR TITLE
hybrid search implementation

### PR DESCRIPTION
**Pull request by StefanTroost**
Hi @ChrisCleaner, I'd like your review on this PR. It implements "hybrid search", a searching strategy in the vector database that combines semantic search with keyword search, see also: https://python.langchain.com/v0.1/docs/modules/data_connection/retrievers/ensemble/

### CODE REVIEW

**Comment by ChrisCleaner** [comment]
Should we write a separate Unit Test for the hybrid search? Or do you reckon it is not necessary right now?

**Comment by StefanTroost** [comment]
Hi @ChrisCleaner, yes good idea. I had not thought of that yet...

**Comment by ChrisCleaner** [comment]
@StefanTroost Should I merge it without the Unit Test alerady or do I wait? 
(I could also write a unit test for it if neessary)

**Comment by StefanTroost** [comment]
Well adding a unit test is a valuable addition. If you have time to add one, that would be great!

**Pull request merged**
